### ISSUE TITLE
New: linesandplanes-directionalvectorsplane part 2

### ISSUE THREAD

**Issue by PHengst** [PRIME-TU-Delft/turborepo-visuals#47]
### Link to paragraph

https://dbalague.pages.ewi.tudelft.nl/openlabook/Chapter1/Lines_and_Planes.html#parametric-vector-equation-of-a-plane

### What type of applet is this?

Interactive applet 2D

### What state is the static image?

No, Dennis has not created a static image yet

### Static image

Under the existing figure 1.26 there is a formula that we want to illustrate further :
![image](https://user-images.githubusercontent.com/72745426/221875380-e19b2346-8081-46da-89ff-57ad3ad468a1.png)
 

### Requirements

see above

### What elements are interactive?

We want another figure 1.23 in terms of PQR with the formula shown, where you can change r and s to show that every point on the plane can be reached. (and a v0 that doesnt crowd the image)

**Comment by juliavdkris** [comment]
Superseded by #86
